# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:38
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170704_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
