# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20170731_1220'),
        ('user', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(blank=True, null=True)),
                ('work_category', models.CharField(choices=[('administration', 'Administrering'), ('backEnd', 'Back End'), ('bugfixing', 'Feilretting'), ('enhancements', 'Forbedrelser'), ('frontEnd', 'Front End'), ('planning', 'Planlegging'), ('system', 'System')], default='administration', max_length=10)),
                ('work_duration', models.TimeField(blank=True, null=True)),
                ('work_note', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
