# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_workhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='work_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
