# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 13:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('get', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='messagerelation',
            managers=[
                ('get', django.db.models.manager.Manager()),
            ],
        ),
    ]
