# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_auto_20170822_1500'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='messagerelation',
            managers=[
            ],
        ),
    ]
