# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0003_auto_20170823_1458'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_msg_id', to='messages.MessageRelation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_user_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
