# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0005_auto_20170824_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
    ]
