# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170717_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('published', 'Publisert'), ('draft', 'Mal')], default='published', max_length=10),
        ),
    ]
