# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20170725_1551'),
        ('project', '0003_auto_20170717_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='project',
            name='publish',
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extent',
            field=models.CharField(choices=[('tiny', 'Mini'), ('small', 'Liten'), ('medium', 'Medium'), ('big', 'Stor'), ('massive', 'Massiv')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='pr_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Lav'), ('medium', 'Medium'), ('high', 'Høy')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Åpen'), ('active', 'Aktiv'), ('finished', 'Ferdig'), ('closed', 'Lukket')], default='open', max_length=10),
        ),
    ]
