# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('none', 'none'), ('team_req_join', 'ønsker å bli med i ditt team')], default='none', max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.CharField(choices=[('none', 'none'), ('team', 'team'), ('project', 'project'), ('user', 'user')], default='none', max_length=10),
        ),
    ]
