# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
