# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170615_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('gender..', 'Gender..'), ('male', 'Male'), ('female', 'Female')], default='gender..', max_length=10),
        ),
    ]
