# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('mann', 'Mann'), ('kvinne', 'Kvinne')], default='mann', max_length=10),
        ),
    ]
