# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamUsers',
            new_name='TeamUser',
        ),
    ]
