# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20170717_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique_for_date='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('hide', 'Skjult'), ('show', 'Vis')], default='hide', max_length=10),
        ),
    ]
