# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170717_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
