# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170717_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('hide', 'Skjult'), ('show', 'Vis')], default='Skjult', max_length=10),
        ),
    ]
