# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20170717_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('hide', 'Skjult'), ('show', 'Vis')], default='show', max_length=10),
        ),
    ]
