# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20170717_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('shown', 'Offentlig'), ('hidden', 'Skjult')], default='shown', max_length=10),
        ),
    ]
