# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20170717_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('public', 'Offentlig'), ('private', 'Skjult')], default='public', max_length=10),
        ),
    ]
