# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_teamjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamjoin',
            name='invited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
