# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('mal', 'Mal'), ('publisert', 'Publisert')], default='mal', max_length=10),
        ),
    ]
